import type { HelpEntry } from '../types';

// App chrome: StatusBar, Preferences, the browser/inspector/timing panels (group: "General").
// Authored during the controls → help-system migration. Ids are stable "general.<fn>" — never rename.
export const chromeHelp: HelpEntry[] = [
  // ── App-level functions (once the menu-ribbon icon group; now menu / rail / dock entries) ────
  {
    id: 'general.outputs',
    title: 'Outputs',
    short: 'Send each surface fullscreen to a projector/display with corner-pin mapping.',
    body: 'Opens the Outputs context, where each surface can be routed to a physical display and warped (corner-pin) onto a real-world screen. Open it when you add or re-align a projector.',
    group: 'General',
    keywords: ['projector', 'display', 'warp', 'corner-pin', 'fullscreen', 'monitor'],
  },
  {
    id: 'general.routing',
    title: 'Routing',
    short: 'Open the Routing spreadsheet — controllers and per-fixture patch.',
    body: 'The Routing spreadsheet lists every controller and the universe/address patch for each fixture in one editable grid. Use it to review or bulk-edit where each fixture sends its DMX.',
    group: 'General',
    keywords: ['patch', 'controllers', 'universe', 'address', 'spreadsheet', 'dmx'],
  },
  {
    id: 'general.dmx-monitor',
    title: 'DMX Monitor',
    short: 'Toggle the DMX Monitor dock — live per-fixture pixel output.',
    body: 'Shows the live per-fixture pixel colours actually being sent out, so you can confirm a fixture is receiving what you expect. Toggle it while diagnosing a dark or wrong-coloured fixture.',
    group: 'General',
    keywords: ['monitor', 'pixels', 'output', 'diagnostic', 'live'],
  },
  {
    id: 'general.preferences',
    title: 'Preferences',
    short: 'Open Preferences — DMX output protocol/target and engine settings.',
    body: 'App-wide settings: DMX protocol and target, engine FPS and gamma, OSC/tracking, UI scale, GPU backend, and the unattended watchdog. These are machine/app settings, not per-project.',
    group: 'General',
    keywords: ['settings', 'options', 'config', 'engine', 'osc', 'watchdog'],
  },
  {
    id: 'general.help',
    title: 'Help panel',
    short: 'Toggle the Help panel — contextual help and topic guides.',
    body: 'Opens the Help panel with contextual hints for whatever you hover plus the searchable topic guides. Press F1 to toggle it any time.',
    group: 'General',
    keywords: ['help', 'guide', 'docs', 'contextual', 'f1'],
    shortcut: 'F1',
  },

  // ── StatusBar ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'general.toggle-left-panel',
    title: 'Toggle left panel',
    short: 'Show or hide the left browser column.',
    body: 'Collapses or restores the left column (the outliners — surfaces, fixtures, groups) to give the viewport more room.',
    group: 'General',
    keywords: ['browser', 'sidebar', 'collapse', 'column', 'outliner'],
  },
  {
    id: 'general.toggle-right-panel',
    title: 'Toggle right panel',
    short: 'Show or hide the right parameter column.',
    body: 'Collapses or restores the right column (the inspector/parameter sections for the current selection) to give the viewport more room.',
    group: 'General',
    keywords: ['inspector', 'sidebar', 'parameters', 'collapse', 'column'],
  },
  {
    id: 'general.show-state',
    title: 'Show state',
    short: 'The show state machine’s current state and elapsed time.',
    body: 'The project state machine runs on its own clock (it can be live with the timeline stopped). This chip shows the active state and how long it has been in it — the always-visible readout of where the show is.',
    group: 'General',
    keywords: ['state machine', 'show', 'elapsed', 'scene', 'transition'],
  },
  {
    id: 'general.preloading',
    title: 'Preloading',
    short: 'The opening content is decoding — the show starts when it is ready.',
    body: 'Between opening a project and arming the show, the app deliberately waits for the opening look to decode. This counter shows that cold-start progress so it does not read as the app ignoring your project.',
    group: 'General',
    keywords: ['cold start', 'boot', 'decode', 'preload', 'loading'],
  },
  {
    id: 'general.render-fps',
    title: 'Render FPS',
    short: 'The renderer’s frame rate (distinct from the output engine rate).',
    body: 'How many frames per second the GPU compositing/mapping loop is producing. This is the renderer’s health; the separate engine readout shows the Art-Net/sACN send rate.',
    group: 'General',
    keywords: ['fps', 'frame rate', 'performance', 'gpu', 'render'],
  },
  {
    id: 'general.output-connection',
    title: 'Output connection',
    short: 'Whether DMX output is live to the target, or offline.',
    body: 'LIVE means frames are being sent to the configured Art-Net/sACN target; OFFLINE means output is stopped or disabled. Hover shows the target address.',
    group: 'General',
    keywords: ['live', 'offline', 'connected', 'artnet', 'sacn', 'target'],
  },
  {
    id: 'general.engine-stats',
    title: 'Engine stats',
    short: 'Native output engine: frames/s, packets/s and universe count.',
    body: 'Live counters from the native send engine: output frame rate (Hz), packets per second, and how many universes are being transmitted. Use it to confirm the engine is pacing as configured.',
    group: 'General',
    keywords: ['pps', 'universes', 'hz', 'packets', 'output', 'engine'],
  },

  // ── Preferences (plain-host settings) ───────────────────────────────────────────────────────
  {
    id: 'general.dmx-target-ip',
    title: 'DMX target IP',
    short: 'The default address DMX frames are sent to.',
    body: 'The unicast IP (or broadcast/multicast, per the toggle below) that all fixtures send to unless a fixture overrides it. Use Discover devices to fill it from a node that replied.',
    group: 'General',
    keywords: ['artnet', 'sacn', 'ip', 'address', 'target', 'node'],
  },
  {
    id: 'general.osc-bind-address',
    title: 'OSC bind address',
    short: 'Bind the OSC receiver to one local network card, or all.',
    body: 'Restrict the OSC/LiDAR listener to a single local NIC (this machine’s IP on the tracking network, e.g. 192.168.61.x). Leave blank to listen on all interfaces.',
    group: 'General',
    keywords: ['osc', 'bind', 'nic', 'interface', 'lidar', 'network'],
  },
  {
    id: 'general.osc-control-prefix',
    title: 'OSC control prefix',
    short: 'The address namespace for external OSC control.',
    body: 'The prefix for external control messages (e.g. /artlux/transport/play). LiDAR blob addresses (/SOL, /MUR, /SOL_MUR) are handled separately and are not affected by this.',
    group: 'General',
    keywords: ['osc', 'prefix', 'namespace', 'control', 'address'],
  },

  // ── Browser column (outliner actions) ───────────────────────────────────────────────────────
  {
    id: 'general.add-surface',
    title: 'Add surface',
    short: 'Add a new stage surface to map content onto.',
    body: 'Creates a new rectangular surface on the stage. A surface holds one piece of content (video, image, effect…) that fixtures then sample their LED colours from.',
    group: 'General',
    keywords: ['surface', 'add', 'new', 'stage', 'mapping'],
  },
  {
    id: 'general.surface-forward',
    title: 'Bring surface forward',
    short: 'Raise this surface in the stage draw order.',
    body: 'The stage composites surfaces low z-index to high, so a higher surface draws on top. Bring forward raises this one so it overlaps the surfaces behind it.',
    group: 'General',
    keywords: ['z-order', 'stacking', 'forward', 'raise', 'layer'],
  },
  {
    id: 'general.surface-backward',
    title: 'Send surface backward',
    short: 'Lower this surface in the stage draw order.',
    body: 'The stage composites surfaces low z-index to high. Send backward lowers this one so overlapping surfaces draw on top of it.',
    group: 'General',
    keywords: ['z-order', 'stacking', 'backward', 'lower', 'layer'],
  },
  {
    id: 'general.select-all-fixtures',
    title: 'Select all fixtures',
    short: 'Select every fixture (the master layer).',
    body: 'Selects all fixtures at once so a look or edit applies to the whole rig. Click a single fixture to narrow the selection again.',
    group: 'General',
    keywords: ['select all', 'master', 'fixtures', 'rig'],
  },
  {
    id: 'general.auto-patch',
    title: 'Auto-patch',
    short: 'Assign universes and addresses to fixtures automatically.',
    body: 'Walks the fixtures in order and packs each one into the next free DMX universe/address, so you do not have to patch by hand. Re-run it after adding fixtures.',
    group: 'General',
    keywords: ['patch', 'universe', 'address', 'assign', 'auto', 'dmx'],
  },
  {
    id: 'general.add-fixture',
    title: 'Add fixture',
    short: 'Add a new LED fixture to the rig.',
    body: 'Creates a new fixture (an LED layout) that you then link to a surface and patch to an output. The fixture samples its per-LED colours from the surface it is mapped to.',
    group: 'General',
    keywords: ['fixture', 'add', 'new', 'led', 'rig'],
  },
  {
    id: 'general.new-group',
    title: 'New group',
    short: 'Make a group from the currently selected fixtures.',
    body: 'Bundles the selected fixtures into a named group so you can recall or apply a look to all of them at once. Add more fixtures to a group later from its row.',
    group: 'General',
    keywords: ['group', 'new', 'selection', 'fixtures'],
  },
  {
    id: 'general.group-add-selected',
    title: 'Add selection to group',
    short: 'Add the currently selected fixture(s) to this group.',
    body: 'Appends whatever is selected on the stage to this existing group, growing its membership without recreating it.',
    group: 'General',
    keywords: ['group', 'add', 'membership', 'selection'],
  },
  {
    id: 'general.group-apply-look',
    title: 'Apply look to group',
    short: 'Copy the selected fixture’s look to every fixture in the group.',
    body: 'Takes the current look (source/effect/colour) of the selected fixture and applies it across the whole group, so the group matches in one click.',
    group: 'General',
    keywords: ['group', 'apply', 'look', 'copy', 'effect'],
  },

  // ── Inspector (parameter-column controls) ───────────────────────────────────────────────────
  {
    id: 'general.fixture-surface',
    title: 'Mapped surface',
    short: 'Which surface this fixture samples its LED colours from.',
    body: 'Links the fixture to one surface; its LEDs read their colours from that surface’s content. Set it to none to turn the fixture off (black output).',
    group: 'General',
    keywords: ['surface', 'mapping', 'sample', 'link', 'fixture'],
  },
  {
    id: 'general.fixture-reverse',
    title: 'Reverse direction',
    short: 'Flip the LED order along the fixture.',
    body: 'Reverses which physical end is LED 0, so content runs the other way along the strip — use it when a fixture was wired or mounted in the opposite direction.',
    group: 'General',
    keywords: ['reverse', 'flip', 'direction', 'order', 'led'],
  },
  {
    id: 'general.color-order',
    title: 'Color order',
    short: 'The per-pixel channel order the fixture expects (RGB, GRB…).',
    body: 'LED chips differ in the byte order they read colour in. Set this to match the fixture (e.g. WS2812 is usually GRB) or reds and greens will be swapped on the real hardware.',
    group: 'General',
    keywords: ['color order', 'rgb', 'grb', 'channel', 'pixel'],
  },
  {
    id: 'general.rgbw-mode',
    title: 'White channel',
    short: 'How the white (W) channel is derived on RGBW fixtures.',
    body: 'On 4-channel RGBW pixels, "Subtract min" pulls the common white component out of R/G/B into the dedicated white LED for cleaner whites; "None" leaves the white channel unused.',
    group: 'General',
    keywords: ['rgbw', 'white', 'channel', 'subtract', 'pixel'],
  },
  {
    id: 'general.serpentine',
    title: 'Serpentine',
    short: 'Alternate row direction on a matrix (zig-zag wiring).',
    body: 'Matrices are often wired boustrophedon — each row runs opposite to the one before. Enable serpentine so the mapping follows that zig-zag instead of every row starting on the same side.',
    group: 'General',
    keywords: ['serpentine', 'zigzag', 'matrix', 'boustrophedon', 'wiring'],
  },
  {
    id: 'general.insert-gap',
    title: 'Insert gap',
    short: 'Split into thirds and mark the middle as an off/dead span.',
    body: 'Carves a dead span out of the fixture (its LEDs output black) by splitting the current segment into thirds and turning the middle off — handy for a physical gap or a dead run of pixels.',
    group: 'General',
    keywords: ['gap', 'dead', 'off', 'segment', 'blank'],
  },
  {
    id: 'general.sparse-output',
    title: 'Sparse output',
    short: 'Skip sending universes whose data has not changed.',
    body: 'Only transmits a universe when its pixel data changes, cutting network traffic on large static rigs. Leave it off if a receiver needs a constant refresh.',
    group: 'General',
    keywords: ['sparse', 'output', 'universe', 'unchanged', 'traffic'],
  },
  {
    id: 'general.fixture-target-ip',
    title: 'Fixture target IP',
    short: 'Override the output address for just this fixture.',
    body: 'Sends this fixture to its own controller instead of the global target. Leave blank to use the global target IP from Preferences.',
    group: 'General',
    keywords: ['target', 'ip', 'override', 'controller', 'fixture', 'address'],
  },

  // ── Timing (the two clocks) ─────────────────────────────────────────────────────────────────
  {
    id: 'general.show-clock',
    title: 'Show clock',
    short: 'Runs continuously — a scene recall does NOT restart it.',
    body: 'The show clock is the project’s master time; it keeps running across scene recalls and cue fires. It is the wrong clock to read a cue’s local timing from — that is the playhead.',
    group: 'General',
    keywords: ['show', 'clock', 'master', 'time', 'state machine'],
  },
  {
    id: 'general.playhead-clock',
    title: 'Playhead',
    short: 'The bound timeline’s own position — restarts on a scene recall.',
    body: 'The playhead is per-document: it resets to zero when a scene’s timeline is recalled. A cue that looks early is almost always the operator reading the show clock instead of this.',
    group: 'General',
    keywords: ['playhead', 'timeline', 'position', 'clock', 'scene'],
  },
];
