import type { HelpEntry } from '../types';

// Stage / surfaces / content-editor / span-editor controls (group: "Content"). Filled during migration.
export const contentHelp: HelpEntry[] = [
  // --- ContentEditor: the source-type picker grid ---
  {
    id: 'content.none',
    title: 'No content',
    short: "Clear this surface's content source.",
    body: 'Sets the surface to None so it outputs nothing. Use it to blank a surface without deleting it.',
    group: 'Content',
    keywords: ['blank', 'empty', 'off'],
  },
  {
    id: 'content.camera',
    title: 'Camera',
    short: "Use a live webcam as this surface's content.",
    body: 'Streams a connected camera onto the surface. The main process must grant camera permission for the feed to appear.',
    group: 'Content',
    keywords: ['webcam', 'video-in', 'live'],
  },
  {
    id: 'content.video',
    title: 'Video file',
    short: "Load a video file as this surface's content.",
    body: 'Pick a video from disk to play on the surface. Supports MP4/MOV and GPU codecs such as HAP.',
    group: 'Content',
    keywords: ['movie', 'mp4', 'mov', 'clip', 'hap'],
  },
  {
    id: 'content.image',
    title: 'Image file',
    short: "Load a still image as this surface's content.",
    body: 'Pick an image from disk to display on the surface.',
    group: 'Content',
    keywords: ['picture', 'still', 'png', 'jpg'],
  },
  {
    id: 'content.dmx-in',
    title: 'DMX In',
    short: 'Drive this surface from incoming Art-Net / sACN.',
    body: 'Uses received DMX universes as the content source, so an external console or another app can feed pixels in.',
    group: 'Content',
    keywords: ['artnet', 'sacn', 'loopback', 'input'],
  },
  {
    id: 'content.spout',
    title: 'Spout',
    short: 'Receive a Spout video stream (Windows GPU share).',
    body: "Captures another app's GPU output over Spout onto this surface. Windows only.",
    group: 'Content',
    keywords: ['gpu', 'share', 'windows'],
  },
  {
    id: 'content.syphon',
    title: 'Syphon',
    short: 'Receive a Syphon video stream (macOS GPU share).',
    body: "Captures another app's GPU output over Syphon onto this surface. macOS only — the Spout "
      + 'sibling. Servers are listed as App — Name, because a Syphon server\'s own name is often '
      + 'blank and the application is what identifies it. Leave it on Active server to follow '
      + 'whichever one is running.',
    group: 'Content',
    keywords: ['gpu', 'share', 'macos', 'mac', 'spout', 'resolume', 'madmapper', 'touchdesigner'],
  },
  {
    id: 'content.ndi',
    title: 'NDI',
    short: 'Receive an NDI network video stream.',
    body: 'Pulls a video source published on the network over NDI onto this surface.',
    group: 'Content',
    keywords: ['network', 'video', 'stream'],
  },
  {
    id: 'content.effect',
    title: 'Effect',
    short: 'Fill the surface with a generative effect.',
    body: 'Runs a GPU generative effect — with a palette, speed and intensity — instead of external media.',
    group: 'Content',
    keywords: ['generative', 'pattern', 'shader'],
  },
  {
    id: 'content.layer',
    title: 'Layer',
    short: 'Show a single timeline track on this surface.',
    body: 'Maps one timeline video layer onto the surface. Choose the track below.',
    group: 'Content',
    keywords: ['timeline', 'track', 'nle'],
  },
  {
    id: 'content.timeline',
    title: 'Timeline',
    short: 'Show the whole timeline composite on this surface.',
    body: 'Maps the full timeline program — all contributing layers composited together — onto the surface.',
    group: 'Content',
    keywords: ['program', 'composite', 'nle'],
  },
  {
    id: 'content.tracking',
    title: 'Tracking',
    short: 'Render LiDAR blob tracking onto this surface.',
    body: 'Draws tracked blobs (projection-mappable) from a LiDAR source, with optional trails and a video background.',
    group: 'Content',
    keywords: ['lidar', 'blob', 'tracking'],
  },
  {
    id: 'content.mediapipe',
    title: 'MediaPipe',
    short: 'Render camera pose tracking (MediaPipe BlazePose).',
    body: 'Uses a webcam and BlazePose to render tracked body poses onto the surface.',
    group: 'Content',
    keywords: ['pose', 'blazepose', 'camera', 'skeleton'],
  },
  {
    id: 'content.augmenta',
    title: 'Augmenta',
    short: 'Render Augmenta optical tracking (OSC).',
    body: 'Draws people tracked by an Augmenta box, received over OSC, onto the surface.',
    group: 'Content',
    keywords: ['optical', 'osc', 'tracking'],
  },
  {
    id: 'content.slice',
    title: 'Slice',
    short: 'Show a cropped region of another surface.',
    body: 'Crops a rectangle out of another surface — how one picture is spanned across several projectors. Choose the source and the crop below.',
    group: 'Content',
    keywords: ['crop', 'region', 'span'],
  },

  // --- ContentEditor: per-type configuration ---
  {
    id: 'content.effect-select',
    title: 'Effect type',
    short: 'Choose which generative effect to run.',
    group: 'Content',
    keywords: ['pattern', 'generative'],
  },
  {
    id: 'content.palette-select',
    title: 'Palette',
    short: 'Choose the colour palette the effect draws with.',
    group: 'Content',
    keywords: ['colours', 'colors'],
  },
  {
    id: 'content.slice-of',
    title: 'Slice of',
    short: 'Choose which surface this slice crops from.',
    body: "The source surface this slice takes its cropped region from. Slices can't nest, so other slices are excluded.",
    group: 'Content',
    keywords: ['source', 'crop'],
  },
  {
    id: 'content.layer-track',
    title: 'Layer track',
    short: 'Choose which timeline track this surface shows.',
    group: 'Content',
    keywords: ['timeline', 'track'],
  },
  {
    id: 'content.tracking-source',
    title: 'Tracking source',
    short: 'Choose the LiDAR zone feeding the blobs.',
    body: 'Selects which tracked region — floor (SOL), wall (MUR) or both — drives the blobs on this surface.',
    group: 'Content',
    keywords: ['lidar', 'sol', 'mur', 'zone'],
  },
  {
    id: 'content.tracking-rotate',
    title: 'Rotate tracking',
    short: 'Rotate the tracking content in 90° steps.',
    body: 'Orients the tracked blobs to match how the LiDAR is mounted relative to the surface.',
    group: 'Content',
    keywords: ['orientation', 'flip'],
  },

  // --- Stage: viewport toolbar ---
  {
    id: 'content.stage-fit',
    title: 'Fit view',
    short: "Fit the view to the surfaces you've placed.",
    body: 'Frames all surfaces in the viewport (rotation-aware). Alt-click resets to the default framing instead.',
    group: 'Content',
    keywords: ['zoom', 'frame', 'fit'],
  },
  {
    id: 'content.stage-reset',
    title: 'Reset view',
    short: 'Reset pan and zoom to the default framing.',
    group: 'Content',
    keywords: ['zoom', 'pan'],
  },
  {
    id: 'content.stage-grid',
    title: 'Toggle grid',
    short: 'Show or hide the placement grid.',
    body: 'Overlays a grid that divides the stage into cells for aligning surfaces and fixtures.',
    group: 'Content',
    keywords: ['guides', 'layout'],
  },
  {
    id: 'content.stage-grid-divisions',
    title: 'Grid divisions',
    short: 'Set how many cells the grid divides the stage into.',
    group: 'Content',
    keywords: ['cells', 'resolution'],
  },
  {
    id: 'content.stage-snap',
    title: 'Toggle snapping',
    short: 'Snap surfaces and fixtures to guides and the grid.',
    body: 'When on, dragging snaps edges and centres to grid lines, other objects and the stage guides.',
    group: 'Content',
    keywords: ['snap', 'magnet', 'align'],
  },

  // --- SpanEditor: spanning one picture across several projectors ---
  {
    id: 'content.span-source',
    title: 'Surface to span',
    short: 'Choose the surface to spread across projectors.',
    body: "Picks the source picture the span cuts into overlapping pieces. A slice can't be a span source.",
    group: 'Content',
    keywords: ['source', 'projectors'],
  },
  {
    id: 'content.span-new',
    title: 'New span',
    short: 'Cut the chosen surface into overlapping projector pieces.',
    body: 'Creates a span: it slices the source into cols×rows overlapping pieces, routes each to a display and sets matching soft edges.',
    group: 'Content',
    keywords: ['add', 'create', 'split'],
  },
  {
    id: 'content.span-align',
    title: 'Align span',
    short: 'Put the alignment grid on every projector of this span.',
    body: "Shows the calibration grid on all of the span's projector outputs at once so you can line up the overlaps.",
    group: 'Content',
    keywords: ['calibrate', 'grid', 'projectors'],
  },
  {
    id: 'content.span-link',
    title: 'Link span',
    short: 'Toggle whether grid changes re-cut the pieces.',
    body: 'Linked: editing cols/rows/overlap re-cuts every piece. Unlinked: pieces keep their hand-tuned crops until you regenerate.',
    group: 'Content',
    keywords: ['link', 'lock', 'relink'],
  },
  {
    id: 'content.span-regenerate',
    title: 'Regenerate span',
    short: 'Re-cut the pieces from the grid.',
    body: 'Rebuilds all pieces from the current grid, discarding any hand-tuned crops.',
    group: 'Content',
    keywords: ['recut', 'refresh', 'rebuild'],
  },
  {
    id: 'content.span-remove',
    title: 'Delete span',
    short: 'Delete the span and the pieces it created.',
    group: 'Content',
    keywords: ['remove', 'trash'],
  },
  {
    id: 'content.span-cols',
    title: 'Columns',
    short: 'Number of columns the span is cut into.',
    group: 'Content',
    keywords: ['grid', 'pieces'],
  },
  {
    id: 'content.span-rows',
    title: 'Rows',
    short: 'Number of rows the span is cut into.',
    group: 'Content',
    keywords: ['grid', 'pieces'],
  },
  {
    id: 'content.span-overlap-x',
    title: 'Overlap X',
    short: 'Fraction of a piece shared with its horizontal neighbour.',
    body: 'The horizontal blend band between neighbouring pieces, as a percentage of piece width.',
    group: 'Content',
    keywords: ['blend', 'soft-edge', 'horizontal'],
  },
  {
    id: 'content.span-overlap-y',
    title: 'Overlap Y',
    short: 'Fraction of a piece shared with its vertical neighbour.',
    body: 'The vertical blend band between neighbouring pieces, as a percentage of piece height.',
    group: 'Content',
    keywords: ['blend', 'soft-edge', 'vertical'],
  },
];
