import type { HelpEntry } from '../types';

// Media panel / asset library controls (group: "Media"). Filled during migration.
export const mediaHelp: HelpEntry[] = [
  {
    id: 'media.import-video',
    title: 'Import Video',
    short: 'Import a video file into the project.',
    body: 'Copies the chosen video into the project’s assets/ folder and registers it in the Media Library. Requires an open project folder.',
    group: 'Media',
    keywords: ['video', 'mp4', 'mov', 'hap', 'import', 'movie', 'clip'],
  },
  {
    id: 'media.import-image',
    title: 'Import Image',
    short: 'Import an image file into the project.',
    body: 'Copies the chosen image into the project’s assets/ folder and registers it in the Media Library. Requires an open project folder.',
    group: 'Media',
    keywords: ['image', 'png', 'jpg', 'jpeg', 'picture', 'import'],
  },
  {
    id: 'media.import-model',
    title: 'Import 3D Model',
    short: 'Import a 3D model into the project.',
    body: 'Copies the chosen model into the project’s assets/ folder for use in the 3D scene. Requires an open project folder.',
    group: 'Media',
    keywords: ['model', '3d', 'glb', 'gltf', 'obj', 'mesh', 'import'],
  },
  {
    id: 'media.import-audio',
    title: 'Import Audio',
    short: 'Import an audio file into the project.',
    body: 'Copies the chosen audio into the project’s assets/ folder and registers it in the Media Library. Requires an open project folder.',
    group: 'Media',
    keywords: ['audio', 'sound', 'wav', 'mp3', 'music', 'import'],
  },
  {
    id: 'media.scan',
    title: 'Scan Assets Folder',
    short: 'Scan the project’s assets folder for media added outside ARTLux.',
    body: 'Adopts files copied into assets/ by hand — via Explorer, a USB drive or a sync tool — so they appear in the library without re-importing. On a venue machine this rescues most of the media.',
    group: 'Media',
    keywords: ['scan', 'rescan', 'adopt', 'refresh', 'folder'],
  },
  {
    id: 'media.view-large',
    title: 'Large Icons',
    short: 'Show the library as large thumbnails.',
    body: 'Explorer-style large-icon density. The choice is saved in the workspace layout, so it persists across restarts.',
    group: 'Media',
    keywords: ['view', 'density', 'thumbnails', 'large', 'grid'],
  },
  {
    id: 'media.view-medium',
    title: 'Medium Icons',
    short: 'Show the library as medium thumbnails.',
    body: 'Explorer-style medium-icon density — more tiles per row. The choice is saved in the workspace layout.',
    group: 'Media',
    keywords: ['view', 'density', 'thumbnails', 'medium', 'grid'],
  },
  {
    id: 'media.view-list',
    title: 'List View',
    short: 'Show the library as a compact list of rows.',
    body: 'A one-row-per-asset list, best for reading many file names at once. The choice is saved in the workspace layout.',
    group: 'Media',
    keywords: ['view', 'list', 'rows', 'compact', 'names'],
  },
  {
    id: 'media.use-on-surface',
    title: 'Use on Surface',
    short: 'Set this asset as the selected surface’s content.',
    body: 'Assigns the selected video or image to the currently selected surface. Select a surface first, or the button stays disabled.',
    group: 'Media',
    keywords: ['use', 'apply', 'surface', 'content', 'assign'],
  },
  {
    id: 'media.reveal-in-folder',
    title: 'Reveal in Folder',
    short: 'Open the asset’s location in the system file browser.',
    body: 'Reveals the file on disk in Explorer / Finder — useful for confirming what a path points at or working on the source file.',
    group: 'Media',
    keywords: ['reveal', 'explorer', 'finder', 'folder', 'show', 'locate'],
  },
  {
    id: 'media.relink',
    title: 'Relink Asset',
    short: 'Locate a moved or missing file and repoint the asset to it.',
    body: 'Use when an asset is missing on disk: browse to the file and the library updates its stored path so every reference resolves again.',
    group: 'Media',
    keywords: ['relink', 'locate', 'missing', 'repair', 'path', 'reconnect'],
  },
  {
    id: 'media.remove',
    title: 'Remove from Library',
    short: 'Remove this asset from the library.',
    body: 'Drops the entry from the Media Library. The file on disk is not deleted. If the asset is still used, a confirmation warns first.',
    group: 'Media',
    keywords: ['remove', 'delete', 'library', 'unregister'],
  },
  {
    id: 'media.asset-chip',
    title: 'Media Item',
    short: 'Drag onto the Stage or Timeline to place this media.',
    body: 'Drag a tile or row onto a surface, the Stage or the Timeline to use it. Double-click a video or image to apply it to the selected surface. Select it to open the inspector below.',
    group: 'Media',
    keywords: ['drag', 'place', 'asset', 'clip', 'tile', 'media'],
  },
];
