import type { HelpEntry } from '../types';

// Routing / controllers / addressing controls (group: "Routing"). Filled during migration.
export const routingHelp: HelpEntry[] = [
  {
    id: 'routing.controller-device',
    title: 'USB DMX interface',
    short: 'Which physical widget this controller sends to.',
    body: 'Lists the USB serial devices attached right now, by their own product name — an ENTTEC DMX '
      + 'USB Pro appears as itself, not as "COM3". Plug the widget in and press the refresh button if it '
      + 'is not listed; devices are enumerated on demand because a widget is usually connected after the '
      + 'app is already open. A port saved in a project but not currently attached stays selected and is '
      + 'marked "not connected", so opening a show on another machine does not silently clear it. '
      + 'ONE WIDGET SENDS ONE UNIVERSE: fixtures auto-patched past it are badged rather than quietly '
      + 'addressed somewhere the device will never transmit. USB DMX requires the native output engine.',
    group: 'Routing',
    keywords: ['usb', 'enttec', 'dmx pro', 'serial', 'com port', 'interface', 'device', 'widget'],
  },
  {
    id: 'routing.auto-patch',
    title: 'Auto-patch',
    short: 'Automatically assign universe + start address to every unlocked fixture.',
    body: 'Packs each auto (unlocked) fixture sequentially per controller; locked rows keep their manual addresses. Addresses may change, so re-upload to the hardware afterwards.',
    group: 'Routing',
    keywords: ['patch', 'address', 'assign', 'pack', 'auto'],
  },
  {
    id: 'routing.reserve-locked',
    title: 'Reserve locked ranges',
    short: 'Pack auto-patched fixtures around locked address ranges instead of through them.',
    body: 'When on, auto-patch reserves the DMX ranges of locked fixtures and routes unlocked fixtures around them. Turning it on re-addresses auto fixtures on the next patch — re-upload to the hardware after.',
    group: 'Routing',
    keywords: ['locked', 'reserve', 'patch policy', 'ranges'],
  },
  {
    id: 'routing.add-controller',
    title: 'Add controller',
    short: 'Add an output controller (device) with its own protocol, IP and universe range.',
    body: 'Controllers are output destinations fixtures can be assigned to. Fixtures left on Global instead use the default target from Preferences.',
    group: 'Routing',
    keywords: ['device', 'output', 'add', 'node'],
  },
  {
    id: 'routing.controller-protocol',
    title: 'Controller protocol',
    short: 'Choose Art-Net or sACN for this controller output.',
    body: 'Sets the DMX-over-network protocol used when sending to this device. Art-Net and sACN differ in addressing and multicast behaviour.',
    group: 'Routing',
    keywords: ['artnet', 'sacn', 'protocol', 'dmx'],
  },
  {
    id: 'routing.controller-ip',
    title: 'Controller IP',
    short: 'Destination IP address for this controller output.',
    body: 'Where DMX packets are unicast for this device. Ignored when Broadcast is on.',
    group: 'Routing',
    keywords: ['ip', 'address', 'unicast', 'destination'],
  },
  {
    id: 'routing.controller-broadcast',
    title: 'Broadcast',
    short: 'Broadcast this controller output instead of unicasting to the IP.',
    body: 'When on, packets go to the subnet broadcast address rather than the specific IP — useful when a node address is unknown or to reach many devices at once.',
    group: 'Routing',
    keywords: ['broadcast', 'bcast', 'subnet'],
  },
  {
    id: 'routing.controller-start-universe',
    title: 'Start universe',
    short: 'First universe number this controller packs its fixtures into.',
    body: 'Auto-patch begins numbering universes here for fixtures assigned to this controller.',
    group: 'Routing',
    keywords: ['universe', 'offset', 'start'],
  },
  {
    id: 'routing.controller-priority',
    title: 'Priority',
    short: 'sACN source priority (0–200) for this controller.',
    body: 'When several sources send the same universe, sACN receivers honour the highest priority. Applies to sACN output.',
    group: 'Routing',
    keywords: ['priority', 'sacn', 'merge'],
  },
  {
    id: 'routing.remove-controller',
    title: 'Remove controller',
    short: 'Delete this controller.',
    body: 'Fixtures assigned to it fall back to the Global Preferences target.',
    group: 'Routing',
    keywords: ['delete', 'remove', 'controller'],
  },
  {
    id: 'routing.fixture-surface',
    title: 'Fixture surface',
    short: 'Link this fixture to the surface it samples its LED colors from.',
    body: 'The fixture reads pixel colors from the mapped region of this surface. Set to off to disable the fixture output.',
    group: 'Routing',
    keywords: ['surface', 'source', 'map', 'link'],
  },
  {
    id: 'routing.fixture-controller',
    title: 'Fixture controller',
    short: 'Assign this fixture to an output controller, or leave it on Global.',
    body: 'Global uses the default target from Preferences; a named controller uses that device protocol, IP and universe range.',
    group: 'Routing',
    keywords: ['controller', 'output', 'assign', 'global'],
  },
  {
    id: 'routing.fixture-universe',
    title: 'Universe',
    short: 'DMX universe for this fixture (editable only when the row is locked).',
    body: 'Auto-assigned per controller; lock the row to set it manually.',
    group: 'Routing',
    keywords: ['universe', 'address', 'dmx'],
  },
  {
    id: 'routing.fixture-start-address',
    title: 'Start address',
    short: 'DMX start channel (1–512) for this fixture (locked rows only).',
    body: 'The first channel within the universe. Auto-assigned unless the row is locked.',
    group: 'Routing',
    keywords: ['address', 'channel', 'start', 'dmx'],
  },
  {
    id: 'routing.fixture-channels',
    title: 'Channels per pixel',
    short: 'Channels per pixel: RGB (3) or RGBW (4).',
    body: 'Determines how many DMX channels each LED consumes and how its color is packed.',
    group: 'Routing',
    keywords: ['rgb', 'rgbw', 'channels', 'pixel'],
  },
  {
    id: 'routing.fixture-leds',
    title: 'LED count',
    short: 'Number of LEDs (pixels) in this fixture.',
    body: 'Drives the fixture DMX footprint — LED count × channels per pixel.',
    group: 'Routing',
    keywords: ['led', 'count', 'pixels'],
  },
  {
    id: 'routing.patch-lock',
    title: 'Lock address',
    short: "Lock this fixture's address so auto-patch won't move it.",
    body: 'Locked rows keep their manual universe/start; unlocked (auto) rows are re-addressed on every auto-patch.',
    group: 'Routing',
    keywords: ['lock', 'manual', 'auto', 'patch'],
  },
];
