import type { HelpEntry } from '../types';

// Scenes & cues (CueBankPanel) controls (group: "Scenes & cues"). Filled during migration.
// The bottom-dock cue-bank grid: row 0 holds Scenes (whole-look snapshots), rows 1+ hold Cues
// (parameter subsets). Live mode fires cells; Edit mode selects and authors them in the inspector.
export const scenesHelp: HelpEntry[] = [
  {
    id: 'scenes.capture-scene',
    title: 'Capture Scene',
    short: 'Snapshot the current look as a new Scene in row 0.',
    body: 'Captures the whole live look (surfaces, fixtures, global brightness) into a new Scene cell on row 0. Recall it later with GO to restore that look. A Scene stores its look as a snapshot; its audio bindings are authored separately.',
    group: 'Scenes & cues',
    keywords: ['snapshot', 'record', 'store', 'look', 'scene'],
  },
  {
    id: 'scenes.mode-live',
    title: 'Live mode',
    short: 'Click a cell to fire the scene or cue it holds.',
    body: 'In Live mode a click on any grid cell fires it — a Scene recalls its look, a Cue applies its parameters. Column headers fire the whole column. Switch to Edit mode to author cells instead of firing them.',
    group: 'Scenes & cues',
    keywords: ['playback', 'fire', 'perform', 'go'],
  },
  {
    id: 'scenes.mode-edit',
    title: 'Edit mode',
    short: 'Click a cell to select and author it in the inspector.',
    body: 'In Edit mode a click selects a Scene or Cue and opens the inspector on the right, where you capture parameters, set fades and transitions. Clicks no longer fire cells — switch back to Live to perform.',
    group: 'Scenes & cues',
    keywords: ['author', 'inspector', 'select', 'design'],
  },
  {
    id: 'scenes.fire-column',
    title: 'Fire column',
    short: 'Fire every scene and cue in this column at once.',
    body: 'The column header fires all cells in that column together, so a single click can trigger a coordinated look built across several rows. Available in both Live and Edit modes.',
    group: 'Scenes & cues',
    keywords: ['column', 'fire all', 'trigger', 'go'],
  },
  {
    id: 'scenes.go',
    title: 'GO (recall scene)',
    short: 'Recall this scene, crossfading the live look to it.',
    body: 'GO recalls the scene, crossfading the live look to its snapshot over the scene fade time. Any audio params bound to the scene fade in alongside it. This is the same action fired by clicking the cell in Live mode.',
    group: 'Scenes & cues',
    keywords: ['recall', 'go', 'trigger', 'fire', 'play scene'],
  },
  {
    id: 'scenes.scene-fade',
    title: 'Scene crossfade',
    short: 'Seconds to crossfade the live look into this scene on GO.',
    body: 'Sets how long (in seconds) the live look takes to crossfade into this scene when recalled. Bound audio params inherit this fade unless a param overrides it. 0 snaps instantly.',
    group: 'Scenes & cues',
    keywords: ['crossfade', 'fade', 'transition', 'seconds', 'duration'],
  },
  {
    id: 'scenes.bind-audio',
    title: 'Bind audio params',
    short: 'Author the audio parameters this scene recalls on GO.',
    body: 'Opens the inspector to bind audio parameters (levels, filters, sends) that this scene recalls on GO. Unlike the look, audio is an explicit list — Update Scene never overwrites it. Requires the audio plugin and clips on the bed.',
    group: 'Scenes & cues',
    keywords: ['audio', 'sound', 'mix', 'levels', 'bind', 'music'],
  },
  {
    id: 'scenes.edit-timeline',
    title: 'Edit scene timeline',
    short: "Open this state's own timeline to author it.",
    body: "Enters authoring mode on the scene's per-state timeline, where you edit the clips and automation that play while this state is active. An accent dot marks the scene currently being authored.",
    group: 'Scenes & cues',
    keywords: ['timeline', 'state', 'author', 'edit', 'clips'],
  },
  {
    id: 'scenes.update-scene',
    title: 'Update scene',
    short: 'Overwrite this scene with the current live look.',
    body: 'Re-captures the current live look into this existing scene, replacing its stored snapshot. The scene keeps its name, column and audio bindings — only the look is refreshed.',
    group: 'Scenes & cues',
    keywords: ['update', 'overwrite', 're-capture', 'refresh', 'save'],
  },
  {
    id: 'scenes.fire-cue',
    title: 'Fire / edit cue',
    short: 'Live mode fires this cue; Edit mode selects it to author.',
    body: 'A Cue applies a subset of parameters over its own fade and transition. In Live mode a click fires it; in Edit mode a click selects it and opens the inspector. Cues layer on top of the current look rather than replacing it wholesale.',
    group: 'Scenes & cues',
    keywords: ['cue', 'fire', 'edit', 'trigger', 'parameters'],
  },
  {
    id: 'scenes.cue-fade',
    title: 'Cue fade',
    short: 'Default fade time (seconds) for this cue on fire.',
    body: "Sets how long this cue's parameters take to reach their captured values when fired. Individual entries can override this with their own per-entry fade below.",
    group: 'Scenes & cues',
    keywords: ['fade', 'time', 'seconds', 'duration', 'cue'],
  },
  {
    id: 'scenes.cue-transition',
    title: 'Cue transition',
    short: 'Interpolation curve used while this cue fades.',
    body: 'Chooses the curve the cue uses while fading to its values: smooth (eased), linear, damper (settling), or none (snap). Per-entry transitions can override this for individual parameters.',
    group: 'Scenes & cues',
    keywords: ['transition', 'curve', 'smooth', 'linear', 'damper', 'ease'],
  },
  {
    id: 'scenes.restart-media',
    title: 'Restart media on fire',
    short: 'Restart surface media from the start when this cue fires.',
    body: "When enabled, firing this cue rewinds the affected surfaces' video/media to the beginning instead of leaving it playing where it was. Use it when a cue should relaunch a clip rather than just retint the look.",
    group: 'Scenes & cues',
    keywords: ['restart', 'media', 'video', 'rewind', 'replay'],
  },
  {
    id: 'scenes.capture-param',
    title: 'Capture parameter',
    short: "Add this parameter's current value to the cue or scene.",
    body: "Captures the parameter's current live value into the open target (a cue's entries, or a scene's audio list). If it is already captured, clicking updates the stored value to the current one.",
    group: 'Scenes & cues',
    keywords: ['capture', 'parameter', 'add', 'value', 'record'],
  },
  {
    id: 'scenes.entry-fade',
    title: 'Per-entry fade',
    short: "This parameter's own fade time; blank inherits the cue/scene fade.",
    body: "Overrides the fade time for this single parameter. Leave it blank to inherit the cue's or scene's fade; a value of 0 is a real override that snaps this param instantly.",
    group: 'Scenes & cues',
    keywords: ['fade', 'per-entry', 'override', 'parameter', 'seconds'],
  },
  {
    id: 'scenes.entry-transition',
    title: 'Per-entry transition',
    short: "This parameter's own interpolation curve; blank inherits the cue/scene.",
    body: "Overrides the transition curve for this single parameter. Leave it blank to inherit the cue's or scene's transition. An automation lane on the same path always wins over this.",
    group: 'Scenes & cues',
    keywords: ['transition', 'per-entry', 'override', 'curve', 'parameter'],
  },
];
