import type { HelpEntry } from '../types';

// The rest of the Timeline NLE controls that timeline.ts does not already cover: the remaining transport
// verbs, the region + hold authoring, view/zoom, tracks & audio-lane creation, the ruler's markers and
// region handles, the track-header layer controls and the clip context actions. All group "Timeline".
// Separate file from timeline.ts so it can be migrated independently. (See help/registry.ts.)
export const timelineExtraHelp: HelpEntry[] = [
  // ── transport ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'timeline.stop',
    title: 'Stop',
    short: 'Pause playback and return to the in-point.',
    body: 'Stops the transport and jumps the playhead back to the in-point (or 0 if no region is set). Goes through the same transport funnel as Play, so OSC and the state machine stay in sync.',
    group: 'Timeline',
    keywords: ['transport', 'pause', 'rewind', 'return', 'reset'],
  },
  {
    id: 'timeline.hold-at-end',
    title: 'Hold at end',
    short: 'Freeze on the last frame instead of stopping at the end.',
    body: 'When on, the picture freezes on its last frame instead of the transport pausing, so the audio bed and the global automation keep playing and the state machine is told the state has finished. Unavailable while Loop is on — a looping timeline never reaches an end.',
    group: 'Timeline',
    keywords: ['freeze', 'hold', 'end', 'state', 'last frame', 'tracker', 'trigger'],
  },
  {
    id: 'timeline.set-in',
    title: 'Set in-point',
    short: 'Set the loop/play region in-point at the playhead.',
    body: 'Marks the start of the playable region at the current playhead. Playback (and Loop) honour the in/out region instead of the whole timeline. Set an out-point past it to define a range.',
    group: 'Timeline',
    keywords: ['in', 'region', 'loop', 'mark', 'range'],
    shortcut: 'I',
  },
  {
    id: 'timeline.set-out',
    title: 'Set out-point',
    short: 'Set the loop/play region out-point at the playhead.',
    body: 'Marks the end of the playable region at the current playhead. An out-point overrides the Length field. With Loop off, playback stops here; with Loop on it wraps back to the in-point.',
    group: 'Timeline',
    keywords: ['out', 'region', 'loop', 'mark', 'range'],
    shortcut: 'O',
  },
  {
    id: 'timeline.end-state',
    title: 'End state here',
    short: 'Set the out-point at the playhead and hold the last frame.',
    body: 'The one-click authoring verb for a tracker-driven show: sets the out-point at the playhead AND turns Hold at end on. The show keeps running while the picture freezes, and the state machine can then advance on a trigger.',
    group: 'Timeline',
    keywords: ['state', 'end', 'hold', 'out', 'trigger', 'tracker', 'freeze'],
  },
  // ── tools ──────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'timeline.select-tool',
    title: 'Select tool',
    short: 'Select, move and trim clips.',
    body: 'The default pointer tool: click a clip to select it, drag it to move, drag its edges to trim. Switch to the Blade tool to cut clips instead.',
    group: 'Timeline',
    keywords: ['select', 'pointer', 'move', 'trim', 'arrow'],
    shortcut: 'V',
  },
  {
    id: 'timeline.add-marker',
    title: 'Add marker',
    short: 'Drop a marker at the playhead.',
    body: 'Adds a marker at the current playhead. Markers are snap targets and navigation cues — click one to seek to it, double-click to add a note, alt-click to delete it.',
    group: 'Timeline',
    keywords: ['marker', 'flag', 'cue', 'note', 'bookmark'],
    shortcut: 'M',
  },
  // ── state-machine control layer ──────────────────────────────────────────────────────────────────
  {
    id: 'timeline.state-machine',
    title: 'State machine layer',
    short: 'Enable the state-machine control layer over this timeline.',
    body: 'Toggles the project state machine (the "Show" graph over scenes) as a control layer, so transitions can be triggered and edited from the timeline. Use Edit logic to author the graph itself.',
    group: 'Timeline',
    keywords: ['state machine', 'fsm', 'show', 'control', 'graph', 'transitions'],
  },
  {
    id: 'timeline.edit-logic',
    title: 'Edit logic',
    short: 'Open the state-machine editor.',
    body: 'Switches to the state-machine workspace to author the show graph — its states, transitions, triggers and rules — over your scenes.',
    group: 'Timeline',
    keywords: ['state machine', 'fsm', 'logic', 'graph', 'edit', 'transitions'],
  },
  // ── document: length / fps ───────────────────────────────────────────────────────────────────────
  {
    id: 'timeline.fps',
    title: 'FPS',
    short: 'Frames per second used for timecode and frame-stepping.',
    body: 'The timeline frame rate. It drives the timecode readout and frame-accurate stepping. A live transport input — committed on Enter or when you leave the field, never per keystroke.',
    group: 'Timeline',
    keywords: ['fps', 'frame rate', 'frames', 'timecode'],
  },
  {
    id: 'timeline.length',
    title: 'Length',
    short: 'The end of the timeline where playback stops or loops.',
    body: 'Sets the timeline duration. Playback stops here — or loops, if Loop is on — unless an out-point overrides it. Committed on Enter or when you leave the field, never per keystroke.',
    group: 'Timeline',
    keywords: ['length', 'duration', 'end', 'time'],
  },
  // ── view / zoom ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'timeline.zoom-out',
    title: 'Zoom out',
    short: 'Show more time in less width.',
    body: 'Zooms the time axis out so more of the timeline is visible. You can also zoom under the cursor with the mouse wheel.',
    group: 'Timeline',
    keywords: ['zoom', 'out', 'scale', 'wheel'],
    shortcut: '-',
  },
  {
    id: 'timeline.zoom-fit',
    title: 'Zoom to fit',
    short: 'Fit the whole timeline into the visible width.',
    body: 'Scales the time axis so all authored content fits in the current viewport width.',
    group: 'Timeline',
    keywords: ['zoom', 'fit', 'all', 'scale'],
  },
  {
    id: 'timeline.zoom-in',
    title: 'Zoom in',
    short: 'Show less time in more width for finer edits.',
    body: 'Zooms the time axis in for frame-accurate editing. You can also zoom under the cursor with the mouse wheel.',
    group: 'Timeline',
    keywords: ['zoom', 'in', 'scale', 'wheel'],
    shortcut: '+',
  },
  // ── tracks / lanes ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'timeline.add-track',
    title: 'Add track',
    short: 'Add a video layer to the timeline.',
    body: 'Adds a new video layer (track) you can drop video, images or effects onto. Higher tracks composite over lower ones.',
    group: 'Timeline',
    keywords: ['track', 'layer', 'add', 'video'],
  },
  {
    id: 'timeline.maximize',
    title: 'Maximize',
    short: 'Expand the timeline to fill the window (toggle).',
    body: 'Toggles the timeline between its docked size and a full-window view for detailed editing. Press again to restore.',
    group: 'Timeline',
    keywords: ['maximize', 'fullscreen', 'expand', 'restore'],
    shortcut: 'F',
  },
  {
    id: 'timeline.add-automation',
    title: 'Add automation lane',
    short: 'Add a keyframe-automation lane for a parameter.',
    body: 'Opens the target picker to add an automation lane — a keyframe curve that drives a chosen parameter (e.g. master gain, an effect value) over the timeline. A lane takes ownership of its parameter.',
    group: 'Timeline',
    keywords: ['automation', 'keyframe', 'curve', 'lane', 'parameter'],
  },
  {
    id: 'timeline.add-audio-track',
    title: 'Add audio track',
    short: 'Add an audio track to THIS timeline.',
    body: 'Adds an audio track bound to this timeline. It rides the playhead and restarts whenever the timeline does — unlike a bed track, which follows the show clock.',
    group: 'Timeline',
    keywords: ['audio', 'track', 'sound', 'timeline'],
  },
  {
    id: 'timeline.add-bed-track',
    title: 'Add bed track',
    short: 'Add a bed track that rides the show clock.',
    body: 'Adds an audio track to the global bed. The bed rides the show clock, so it does NOT restart on a scene recall — use it for continuous house music underneath the scenes.',
    group: 'Timeline',
    keywords: ['bed', 'audio', 'track', 'show clock', 'house'],
  },
  {
    id: 'timeline.edit-scene',
    title: 'Editing (scene selector)',
    short: 'Choose which timeline to edit — global or a scene.',
    body: 'Picks which timeline is bound to the editor: the global (show) timeline or a scene’s own. Selecting a scene recalls it live — its look, its fade and its timeline.',
    group: 'Timeline',
    keywords: ['scene', 'state', 'timeline', 'editing', 'recall', 'global'],
  },
  {
    id: 'timeline.save-state',
    title: 'Save to state',
    short: 'Re-capture the current look into this state.',
    body: 'Saves the current look back into the active state (scene), so what is on stage now becomes what that state recalls.',
    group: 'Timeline',
    keywords: ['save', 'state', 'scene', 'capture', 'look'],
  },
  // ── ruler: region handles + markers ──────────────────────────────────────────────────────────────
  {
    id: 'timeline.region-in',
    title: 'In-point handle',
    short: 'Drag to move the region in-point.',
    body: 'The start of the playable / loop region on the ruler. Drag it to move where playback (and Loop) begins. Set it at the playhead with the Set in-point button or the I key.',
    group: 'Timeline',
    keywords: ['in', 'region', 'loop', 'handle', 'drag'],
  },
  {
    id: 'timeline.region-out',
    title: 'Out-point handle',
    short: 'Drag to move the region out-point (or the state end).',
    body: 'The end of the playable / loop region on the ruler. Drag it to move where playback stops or loops. When Hold at end is on it marks the state end — the picture freezes here while the show plays on.',
    group: 'Timeline',
    keywords: ['out', 'region', 'loop', 'handle', 'drag', 'state end', 'hold'],
  },
  {
    id: 'timeline.marker',
    title: 'Marker',
    short: 'Click to seek; double-click to note; alt-click to delete.',
    body: 'A marker on the ruler. Click it to seek there, double-click to edit its note, and alt-click (or right-click) to delete it. Markers are also snap targets for edits.',
    group: 'Timeline',
    keywords: ['marker', 'flag', 'cue', 'note', 'seek', 'delete'],
  },
  // ── track header: layer controls ─────────────────────────────────────────────────────────────────
  {
    id: 'timeline.track-mute',
    title: 'Mute (visual)',
    short: 'Hide this track from the Program composite.',
    body: 'Mutes the track in the visual Program composite — its clips stop contributing to the picture. This is a picture flag, separate from silencing the track’s video audio.',
    group: 'Timeline',
    keywords: ['mute', 'track', 'visual', 'program', 'hide'],
  },
  {
    id: 'timeline.track-solo',
    title: 'Solo (visual)',
    short: 'Show only soloed tracks in the Program composite.',
    body: 'Solos the track in the visual Program composite — while any track is soloed, only soloed tracks contribute to the picture.',
    group: 'Timeline',
    keywords: ['solo', 'track', 'visual', 'program', 'isolate'],
  },
  {
    id: 'timeline.track-lock',
    title: 'Lock track',
    short: 'Prevent edits to this track’s clips.',
    body: 'Locks the track so its clips can’t be moved, trimmed, bladed or deleted — a guard against accidental edits during a show. Unlock to edit again.',
    group: 'Timeline',
    keywords: ['lock', 'track', 'protect', 'freeze', 'edit'],
  },
  {
    id: 'timeline.track-hide',
    title: 'Show / hide track',
    short: 'Toggle whether this track is rendered.',
    body: 'Enables or disables the track’s output. A hidden track is skipped by the renderer — distinct from Mute, which is a composite flag.',
    group: 'Timeline',
    keywords: ['hide', 'show', 'track', 'enable', 'disable', 'eye', 'visible'],
  },
  {
    id: 'timeline.track-audio-mute',
    title: 'Mute track audio',
    short: 'Silence the soundtracks of this track’s video clips.',
    body: 'Mutes the audio carried by the video clips on this track. Separate from the visual Mute — hiding a layer does not silence it, and silencing it does not hide it.',
    group: 'Timeline',
    keywords: ['audio', 'mute', 'track', 'sound', 'video audio'],
  },
  {
    id: 'timeline.track-blend',
    title: 'Opacity & blend',
    short: 'Set this track’s opacity and blend mode.',
    body: 'Opens a popover to set the track’s opacity and blend mode (normal / add / screen / multiply) in the Timeline (Program) composite.',
    group: 'Timeline',
    keywords: ['opacity', 'blend', 'mix', 'composite', 'track', 'transparency'],
  },
  {
    id: 'timeline.track-remove',
    title: 'Delete track',
    short: 'Remove this track and all its clips.',
    body: 'Deletes the track from the timeline along with every clip on it. There is no per-edit undo for this in the show path, so use with care.',
    group: 'Timeline',
    keywords: ['delete', 'remove', 'track', 'layer', 'trash'],
  },
  // ── clip context actions ─────────────────────────────────────────────────────────────────────────
  {
    id: 'timeline.clip-remove',
    title: 'Delete clip',
    short: 'Remove the selected clip from its lane.',
    body: 'Deletes the selected clip. Use the Delete key for a lift delete (leaves a gap) or a ripple delete (closes the gap) depending on your shortcut.',
    group: 'Timeline',
    keywords: ['delete', 'remove', 'clip', 'trash', 'lift'],
  },
];
