import { app } from 'electron';
import { readFile, readdir, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { FixtureProfile, FixtureProfileSummary } from '../../shared/protocol';

// Main-side backend for the DMX fixture library.
//
// TWO SOURCES, one catalogue:
//   · the BUNDLED set — generated by scripts/build-fixture-library.mjs from the Open Fixture Library
//     and shipped as electron-builder extraResources. Read-only, ~4 MB of JSON across one file per
//     manufacturer plus a small index;
//   · the USER set — userData/fixture-profiles/*.json: profiles imported from a .gdtf/.qxf, extracted
//     from a supplier PDF, or authored by hand. Writable, and it WINS on id, so an operator can
//     correct a shipped profile without editing the bundle (which the next build would overwrite).
//
// WHY MAIN OWNS THIS. The renderer is sandboxed (no fs), and the full library must never be imported
// into the renderer bundle — several MB of JSON in a bundle that hot-reloads would slow every edit
// for data that is only needed when someone patches a fixture. So the renderer gets the small index
// eagerly and pulls one manufacturer's profiles on demand.

// Where the bundled library lives. In dev that is the repo working tree under `resources/`; in a
// packaged build electron-builder copies it to `<resources>/fixture-library` (note: NO `resources/`
// prefix there, because process.resourcesPath already IS that directory). Mirrors main/docs.ts.
function bundledRoot(): string {
  return app.isPackaged
    ? join(process.resourcesPath || app.getAppPath(), 'fixture-library')
    : join(app.getAppPath(), 'resources', 'fixture-library');
}

function userRoot(): string {
  return join(app.getPath('userData'), 'fixture-profiles');
}

// Caches. The bundled set is immutable for the life of the process, so it is cached hard. The user
// set is re-read whenever it might have changed (see invalidateUserProfiles) because the operator can
// import a profile mid-session and must not have to restart to see it.
let indexCache: FixtureProfileSummary[] | null = null;
const manufacturerCache = new Map<string, FixtureProfile[]>();
let userCache: FixtureProfile[] | null = null;

async function readJson<T>(path: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(path, 'utf-8')) as T;
  } catch {
    // A missing or corrupt file must never take the app down — the library is a convenience, and a
    // fixture can always be patched by hand. Callers degrade to "fewer profiles", never to a crash.
    return null;
  }
}

/** Every profile in userData/fixture-profiles. One file may hold a single profile or an array. */
async function readUserProfiles(): Promise<FixtureProfile[]> {
  if (userCache) return userCache;
  const dir = userRoot();
  const out: FixtureProfile[] = [];
  if (existsSync(dir)) {
    let names: string[] = [];
    try { names = await readdir(dir); } catch { names = []; }
    for (const name of names.sort()) {
      if (!name.endsWith('.json')) continue;
      const parsed = await readJson<FixtureProfile | FixtureProfile[]>(join(dir, name));
      if (!parsed) { console.warn(`[fixture-library] skipping unreadable user profile ${name}`); continue; }
      for (const p of Array.isArray(parsed) ? parsed : [parsed]) {
        // The minimum that makes a profile usable at all. Anything less and it would produce a
        // fixture with an unknown footprint, which is worse than not offering it.
        if (p && typeof p.id === 'string' && Array.isArray(p.modes) && p.modes.length && Array.isArray(p.channels)) out.push(p);
        else console.warn(`[fixture-library] skipping malformed user profile in ${name}`);
      }
    }
  }
  userCache = out;
  return out;
}

const summarize = (p: FixtureProfile): FixtureProfileSummary => ({
  id: p.id,
  manufacturer: p.manufacturer,
  model: p.model,
  ...(p.aliases?.length ? { aliases: p.aliases } : {}),
  ...(p.categories?.length ? { categories: p.categories } : {}),
  modes: p.modes.map((m) => ({ key: m.key, name: m.name, footprint: m.footprint })),
  verified: p.verified,
  origin: p.source?.origin,
});

/** The whole catalogue: bundled rows, then user rows layered over them by id. */
export async function getIndex(): Promise<FixtureProfileSummary[]> {
  if (indexCache) return indexCache;
  const bundled = await readJson<FixtureProfileSummary[]>(join(bundledRoot(), 'index.json'));
  if (!bundled) {
    // Loud, once, and then carry on with whatever the operator has locally. A missing bundle means
    // the extraResources entry did not ship — exactly the silent-skip failure
    // scripts/verify-package-resources.cjs exists to catch, so say so rather than look empty.
    console.warn(`[fixture-library] no bundled index at ${bundledRoot()} — only user profiles will be offered`);
  }
  const rows = new Map<string, FixtureProfileSummary>();
  for (const row of bundled ?? []) rows.set(row.id, row);
  for (const p of await readUserProfiles()) rows.set(p.id, summarize(p));
  indexCache = [...rows.values()].sort((a, b) =>
    a.manufacturer.localeCompare(b.manufacturer) || a.model.localeCompare(b.model));
  return indexCache;
}

/** Full profiles for one manufacturer key, user profiles layered over bundled ones by id. */
export async function getManufacturer(key: string): Promise<FixtureProfile[]> {
  // The key becomes a filename, so it must not be able to escape the library directory.
  if (!/^[a-z0-9][a-z0-9-]*$/i.test(key)) return [];
  const cached = manufacturerCache.get(key);
  const bundled = cached ?? (await readJson<FixtureProfile[]>(join(bundledRoot(), `${key}.json`)) ?? []);
  if (!cached) manufacturerCache.set(key, bundled);

  const byId = new Map<string, FixtureProfile>();
  for (const p of bundled) byId.set(p.id, p);
  for (const p of await readUserProfiles()) if (p.id.split('/')[0] === key) byId.set(p.id, p);
  return [...byId.values()];
}

/** Resolve one profile by id, whichever source holds it. */
export async function getProfile(id: string): Promise<FixtureProfile | null> {
  const key = id.split('/')[0];
  if (!key) return null;
  return (await getManufacturer(key)).find((p) => p.id === id) ?? null;
}

/**
 * Drop the user-profile cache (and the index that layers it). Call after writing a profile into
 * userData, so an import shows up without a restart.
 */
export function invalidateUserProfiles(): void {
  userCache = null;
  indexCache = null;
}

/** Ensure userData/fixture-profiles exists, so the import paths can just write into it. */
export async function ensureUserDir(): Promise<string> {
  const dir = userRoot();
  await mkdir(dir, { recursive: true }).catch(() => undefined);
  return dir;
}
