#!/usr/bin/env node
/*
 * Copy the app's design tokens into the launcher.
 *
 * WHY GENERATED, NOT COPIED BY HAND. The launcher is a separate product with its own build and
 * cannot import from src/renderer, so it needs its own copy of tokens.css. A hand-written copy is a
 * fork with no mechanism to notice it has drifted — and it drifted immediately: the first version of
 * this file carried --accent-hover #3fc9d6 and --accent-press #1f9aa6 against the app's #34c8d6 and
 * #1f97a3, an --accent-dim that was an opaque teal instead of a 14% tint, and renamed half the
 * tokens (--fg-1 for --text-1, --radius-md for --r-md, --shadow-e1 for --e-1). None of that is
 * visible in a screenshot; it just makes the launcher quietly a different product.
 *
 * Regenerating on every build means the launcher's tokens ARE the app's tokens, always. The copy is
 * gitignored and this runs from `npm run build` and `npm run dev`, both of which Tauri invokes
 * itself (beforeBuildCommand / beforeDevCommand), so nothing can bundle a stale one.
 */
const fs = require('node:fs');
const path = require('node:path');

const src = path.join(__dirname, '..', '..', 'src', 'renderer', 'styles', 'tokens.css');
const dst = path.join(__dirname, '..', 'src', 'tokens.css');

if (!fs.existsSync(src)) {
  console.error(`\x1b[31m✗\x1b[0m sync-tokens: ${src} does not exist — cannot style the launcher like the app.`);
  process.exit(1);
}

const header = `/* GENERATED by launcher/scripts/sync-tokens.cjs — DO NOT EDIT.
 * Source of truth: src/renderer/styles/tokens.css (spec: docs/DESIGN-SYSTEM.md).
 * Change a value THERE; this file is overwritten on every launcher build.
 */
`;
const body = fs.readFileSync(src, 'utf8');
const out = header + body;

const before = fs.existsSync(dst) ? fs.readFileSync(dst, 'utf8') : null;
fs.writeFileSync(dst, out);
console.log(
  before === out
    ? `\x1b[32m✓\x1b[0m sync-tokens: already current`
    : `\x1b[32m✓\x1b[0m sync-tokens: refreshed from src/renderer/styles/tokens.css`,
);
